name: Sales_Force_App
description: A Flutter mobile dashboard application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  get: ^4.6.5
  font_awesome_flutter: ^10.4.0
  flutter_vector_icons: ^2.0.0
  image_picker: ^0.8.7+4
  http: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true